# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87924268aaaf8f8a90677892ca0d143c3a5ba743e39fcf51c52d5414cc1d9d9e24741a90c7fb76d3cfa6e39f8e7c41404f8f43b79b30c5a265181809a9aa991d

test:
  secret_key_base: a547316fd1c4d971ed6fe6992fca6dc6ee62d7823256727d18efbaaf9adae3afe1a15e2d84be1e4db2d32b9bb2afa22fb4ba4d6c7f8eb60ad885038451188003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
